# Generated by Django 5.1.4 on 2025-06-10 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'Отличное'), ('used', 'Хорошее'), ('refurbished', 'С реставрацией'), ('broken', 'Требует реставрации'), ('other', 'Другое')], default='used', max_length=100, verbose_name='Состояние'),
        ),
        migrations.AddField(
            model_name='product',
            name='detail_text',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Подробнее'),
        ),
        migrations.AddField(
            model_name='product',
            name='mainimage',
            field=models.ImageField(blank=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='product',
            name='preview_text',
            field=models.TextField(blank=True, max_length=200, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='production_date',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='Годы выпуска'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
